baseURL = "https://gobinath.com/"
languageCode = "en-us"
title = "Gobinath Mallaiyan"
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[build]
  [build.buildStats]
    enable = true

[params]
  description = "Technical Program Manager | AI/ML Enthusiast | Aspiring CTO"
  author = "Gobinath Mallaiyan"
  formspreeID = "xeegwavv"

  [params.social]
    linkedin = "https://www.linkedin.com/in/gobinathm/"
    github = "https://github.com/gobinathm"
    instagram = "https://www.instagram.com/gobinathm/"
    medium = "https://medium.com/@gobinathm"
    stackoverflow = "https://stackoverflow.com/users/1288968/gobinath-mallaiyan"
    twitter = "https://twitter.com/gobinathm"
    fivehundredpx = "https://500px.com/p/gobinathm"
    strava = "https://www.strava.com/athletes/10286114"
    goodreads = "https://www.goodreads.com/user/show/12583429-gobinath-mallaiyan"
    storygraph = "https://app.thestorygraph.com/profile/gobinathm"
